### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by toniss** [secretsquirrel/BDFProxy#29]
testing on Kali Sana the script starts fine but at any request prints something like this (configured as upstream proxy)
********** REQUEST **********
[*] HOST: tiles.services.mozilla.com
[*] PATH: None
********** END REQUEST **********
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 135, in handle
    **conn_kwargs).handle_messages()
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1035, in handle_messages
    while self.handle_flow():
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1124, in handle_flow
    self.process_server_address(flow)
  File "/usr/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1375, in process_server_address
    for s in flow.server_conn.state:
AttributeError: 'NoneType' object has no attribute 'state'
mitmproxy has crashed!

**Comment by secretsquirrel** [comment]
I haven't tested it with upstream.

Do you have the same error with transparent mode?

Also what's your upstream setup?

Website---BDFProxy----anotherProxy---User?

**Comment by secretsquirrel** [comment]
No response... closing
